export interface DemoLine {
  type: "line" | "header" | "box" | "gap" | "stats";
  text?: string;
  style?: "info" | "success" | "command" | "accent" | "muted" | "link" | "warn";
  timing?: string;
  url?: string;
  lines?: string[];
  title?: string;
  stats?: { txCount: number; trafficCC: string; totalMs: number };
}

const party = (name: string) => `${name}::12204bcabe5f617d26d082a442b560d61e60e57ad845260b01c98657285eeeb2e7ef`;
const tx = (n: number) => `20260320${String(n).padStart(8, "0")}:0`;

export const FALLBACK_SCENARIOS: Record<string, DemoLine[]> = {
  "earn-save": [
    { type: "line", text: "Creating demo agent...", style: "info" },
    { type: "line", text: `✓ Party: ${party("demo_earn").slice(0, 30)}...`, style: "success", timing: "380ms" },
    { type: "line", text: "✓ Funded: 10.000000 USDCx from faucet", style: "success" },
    { type: "gap" },
    { type: "header", text: "── Agent receives client payment ──" },
    { type: "gap" },
    { type: "line", text: "Incoming: 5.000000 USDCx from client_0x8b", style: "info" },
    { type: "line", text: "→ TransferFactory.Transfer: client → demo_earn", style: "command" },
    { type: "line", text: `✓ Canton tx: ${tx(1)}`, style: "success", timing: "240ms" },
    { type: "line", text: `  ↳ verify: ccview.io/tx/${tx(1)}`, style: "link", url: `https://ccview.io/tx/${tx(1)}` },
    { type: "gap" },
    { type: "header", text: "── Auto-deposit to savings (80% rule) ──" },
    { type: "gap" },
    { type: "line", text: "Calculating: 5.000000 × 80% = 4.000000 USDCx", style: "info" },
    { type: "line", text: "→ caypo savings deposit 4.000000", style: "command" },
    { type: "line", text: "→ TransferFactory.Transfer: checking → savings", style: "command" },
    { type: "line", text: `✓ Canton tx: ${tx(2)}`, style: "success", timing: "220ms" },
    { type: "gap" },
    { type: "box", title: "Account Summary", lines: [
      "Checking    $11.000000 USDCx   (+1.00 from payment)",
      "Savings     $4.000000 USDCx    4.21% APY",
      "Total       $15.000000 USDCx",
      "",
      "Projected yearly savings yield: ~$0.168 USDCx",
    ]},
    { type: "gap" },
    { type: "stats", stats: { txCount: 2, trafficCC: "0.002", totalMs: 840 } },
  ],

  "borrow-compute": [
    { type: "line", text: "Creating demo agent...", style: "info" },
    { type: "line", text: `✓ Party: ${party("demo_credit").slice(0, 32)}...`, style: "success", timing: "360ms" },
    { type: "line", text: "✓ Funded: 0.500000 USDCx checking", style: "success" },
    { type: "line", text: "✓ Funded: 5.000000 USDCx savings (collateral)", style: "success" },
    { type: "gap" },
    { type: "header", text: "── Agent needs GPU compute ──" },
    { type: "gap" },
    { type: "line", text: "Task: Generate product image via fal.ai FLUX Pro", style: "info" },
    { type: "line", text: "Cost: 2.000000 USDCx", style: "info" },
    { type: "line", text: "Checking balance: 0.500000 — insufficient!", style: "warn" },
    { type: "gap" },
    { type: "header", text: "── Borrow from credit (against savings) ──" },
    { type: "gap" },
    { type: "line", text: "→ caypo credit borrow 2.000000", style: "command" },
    { type: "line", text: "Collateral: 5.000000 USDCx in savings", style: "info" },
    { type: "line", text: "Health factor: 2.50 (healthy — above 1.5 threshold)", style: "info" },
    { type: "line", text: `✓ Canton tx: ${tx(3)}`, style: "success", timing: "260ms" },
    { type: "gap" },
    { type: "header", text: "── Pay for fal.ai via CAYPO Gateway ──" },
    { type: "gap" },
    { type: "line", text: "POST mpp.caypo.xyz/fal/v1/generate", style: "command" },
    { type: "line", text: "← 402 Payment Required", style: "accent" },
    { type: "line", text: '  amount="2.000000" currency="USDCx" method="canton"', style: "muted" },
    { type: "line", text: `✓ Canton tx: ${tx(4)}`, style: "success", timing: "230ms" },
    { type: "line", text: "← 200 OK", style: "success" },
    { type: "gap" },
    { type: "box", title: "fal.ai Response", lines: [
      "model: flux-pro",
      "image: product-hero.png (1024x1024)",
      "inference_time: 3.2s",
      "seed: 42981",
    ]},
    { type: "gap" },
    { type: "header", text: "── Client pays for completed work ──" },
    { type: "gap" },
    { type: "line", text: "Incoming: 5.000000 USDCx from client_0x4f", style: "info" },
    { type: "line", text: `✓ Canton tx: ${tx(5)}`, style: "success", timing: "240ms" },
    { type: "gap" },
    { type: "header", text: "── Repay credit ──" },
    { type: "gap" },
    { type: "line", text: "→ caypo credit repay 2.000000", style: "command" },
    { type: "line", text: "Interest accrued: 0.000027 USDCx (7.83% APR, 1 min)", style: "muted" },
    { type: "line", text: `✓ Canton tx: ${tx(6)}`, style: "success", timing: "210ms" },
    { type: "gap" },
    { type: "box", title: "Account Summary", lines: [
      "Checking    $3.499973 USDCx",
      "Savings     $5.000000 USDCx   4.21% APY",
      "Credit      $0.000000 USDCx   ✓ fully repaid",
      "Health      ∞ (no debt)",
      "Net profit  +$2.999973 USDCx",
    ]},
    { type: "gap" },
    { type: "stats", stats: { txCount: 5, trafficCC: "0.005", totalMs: 1200 } },
  ],

  "swap-invest": [
    { type: "line", text: "Creating demo agent...", style: "info" },
    { type: "line", text: `✓ Party: ${party("demo_invest").slice(0, 33)}...`, style: "success", timing: "340ms" },
    { type: "line", text: "✓ Funded: 100.000000 USDCx checking", style: "success" },
    { type: "gap" },
    { type: "header", text: "── Swap USDCx → CC ──" },
    { type: "gap" },
    { type: "line", text: "→ caypo exchange swap --from USDCx --to CC --amount 50", style: "command" },
    { type: "line", text: "Quote: 50.000000 USDCx → 340.136054 CC", style: "info" },
    { type: "line", text: "Rate: 1 CC = $0.147 USDCx", style: "info" },
    { type: "line", text: "Slippage: 0.12% (max: 0.50%)", style: "muted" },
    { type: "line", text: `✓ Canton tx: ${tx(7)}`, style: "success", timing: "280ms" },
    { type: "gap" },
    { type: "header", text: '── Invest in "Canton Validator" strategy ──' },
    { type: "gap" },
    { type: "line", text: '→ caypo invest buy --strategy "canton-validator" --amount 200 --asset CC', style: "command" },
    { type: "line", text: "Strategy: 60% validator staking + 40% DeFi yield", style: "info" },
    { type: "line", text: `✓ Canton tx: ${tx(8)}`, style: "success", timing: "250ms" },
    { type: "gap" },
    { type: "header", text: "── Set up DCA (Dollar-Cost Average) ──" },
    { type: "gap" },
    { type: "line", text: "→ caypo invest dca --amount 10 --asset CC --freq weekly", style: "command" },
    { type: "line", text: "✓ DCA configured: 10 USDCx → CC every Monday 00:00 UTC", style: "success" },
    { type: "line", text: "Next execution: Mon Mar 23, 2026", style: "muted" },
    { type: "gap" },
    { type: "box", title: "Portfolio Summary", lines: [
      "Checking    $50.000000 USDCx",
      "Exchange    140.136054 CC ($20.60)",
      "Investment  200.000000 CC ($29.40)",
      "  └ Strategy: Canton Validator (+2.3% projected)",
      "DCA Active  $10/week → CC",
      "",
      "Total portfolio: ~$100.00",
    ]},
    { type: "gap" },
    { type: "stats", stats: { txCount: 2, trafficCC: "0.002", totalMs: 870 } },
  ],

  "multi-agent": [
    { type: "line", text: "Creating demo agents...", style: "info" },
    { type: "line", text: `✓ Agent A: ${party("demo_alice").slice(0, 32)}...`, style: "success", timing: "360ms" },
    { type: "line", text: `✓ Agent B: ${party("demo_bob").slice(0, 30)}...`, style: "success", timing: "340ms" },
    { type: "line", text: "✓ Funded Agent A: 100.000000 USDCx", style: "success" },
    { type: "line", text: "✓ Funded Agent B: 0.000000 USDCx (new agent)", style: "muted" },
    { type: "gap" },
    { type: "header", text: "── Agent A sends payment to Agent B ──" },
    { type: "gap" },
    { type: "line", text: "→ caypo send 25.000000 --to demo_bob", style: "command" },
    { type: "line", text: "Safeguard check: $25.00 < $1,000/tx limit ✓", style: "info" },
    { type: "line", text: "Daily usage: $25.00 / $5,000.00 (0.5%)", style: "muted" },
    { type: "line", text: `✓ Canton tx: ${tx(9)}`, style: "success", timing: "260ms" },
    { type: "line", text: `  ↳ verify: ccview.io/tx/${tx(9)}`, style: "link", url: `https://ccview.io/tx/${tx(9)}` },
    { type: "gap" },
    { type: "header", text: "── Agent B auto-deposits to savings ──" },
    { type: "gap" },
    { type: "line", text: "Agent B rule: auto-save 100% of incoming (new agent)", style: "info" },
    { type: "line", text: "→ caypo savings deposit 25.000000", style: "command" },
    { type: "line", text: `✓ Canton tx: ${tx(10)}`, style: "success", timing: "230ms" },
    { type: "gap" },
    { type: "box", title: "Agent A", lines: [
      "Checking    $75.000000 USDCx",
      "Daily limit $25.00 / $5,000.00 used",
      "Tx limit    $25.00 < $1,000.00 ✓",
    ]},
    { type: "box", title: "Agent B", lines: [
      "Checking    $0.000000 USDCx",
      "Savings     $25.000000 USDCx  4.21% APY",
      "Total       $25.000000 USDCx",
    ]},
    { type: "gap" },
    { type: "line", text: "Privacy: Only Alice and Bob see this transaction.", style: "accent" },
    { type: "line", text: "No public ledger exposure. Canton privacy by default.", style: "muted" },
    { type: "gap" },
    { type: "stats", stats: { txCount: 2, trafficCC: "0.002", totalMs: 850 } },
  ],
};
